name: Baseline Policy Enforcement

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  baseline-check:
    runs-on: ubuntu-latest
    name: Baseline Policy Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Download Baseline
      run: |
        curl -L -o baseline https://github.com/johndansu/Baseline/releases/download/v1.0.0/baseline-linux-amd64
        chmod +x baseline
        
    - name: Run Baseline Check
      run: |
        ./baseline check
        echo "Baseline check completed with exit code: $?"
        
    - name: Run Baseline Scan
      run: |
        ./baseline scan --format json > baseline-results.json
        echo "Baseline scan results:"
        cat baseline-results.json
        
    - name: Upload Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: baseline-results
        path: baseline-results.json
        
    - name: Comment PR with Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('baseline-results.json')) {
            const results = JSON.parse(fs.readFileSync('baseline-results.json', 'utf8'));
            const violations = results.policy_violations || 0;
            
            if (violations > 0) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🚨 Baseline Policy Violations Found\n\nBaseline detected ${violations} policy violations that must be fixed before this PR can be merged.\n\n### Required Actions:\n- [ ] Fix all policy violations\n- [ ] Re-run Baseline check\n- [ ] Ensure all tests pass\n\n### Violation Details:\n\`\`\`json\n${JSON.stringify(results, null, 2)}\n\`\`\`\n\n---\n*This comment was generated by Baseline v1.0.0*`
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## ✅ Baseline Policy Check Passed\n\nNo policy violations detected. This PR is ready for review.\n\n---\n*This comment was generated by Baseline v1.0.0*'
              });
            }
          }
          
  baseline-enforcement:
    runs-on: ubuntu-latest
    name: Baseline Enforcement
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Download Baseline
      run: |
        curl -L -o baseline https://github.com/johndansu/Baseline/releases/download/v1.0.0/baseline-linux-amd64
        chmod +x baseline
        
    - name: Enforce Policies
      run: |
        ./baseline enforce
        echo "Policy enforcement completed with exit code: $?"
