name: Baseline Policy Enforcement

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

env:
  GO_VERSION: "1.24"

jobs:
  baseline-check:
    name: Baseline Policy Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build Baseline binary
        run: |
          go mod download
          go build -trimpath -o baseline ./cmd/baseline
          chmod +x baseline

      - name: Run Baseline check
        run: ./baseline check

      - name: Run Baseline report (JSON)
        if: always()
        run: ./baseline report --json > baseline-results.json

      - name: Upload results artifact
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: baseline-results
          path: baseline-results.json
          if-no-files-found: error

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const fs = require('fs');
            if (!fs.existsSync('baseline-results.json')) {
              return;
            }

            const results = JSON.parse(fs.readFileSync('baseline-results.json', 'utf8'));
            const violations = Array.isArray(results.violations) ? results.violations.length : 0;
            const securityIssues = Number(results.security_issues || 0);
            const filesScanned = Number(results.files_scanned || 0);

            const summary = [
              '## Baseline Policy Check',
              '',
              `- Files scanned: ${filesScanned}`,
              `- Security issues: ${securityIssues}`,
              `- Policy violations: ${violations}`,
              ''
            ];

            if (violations > 0) {
              const details = results.violations
                .slice(0, 20)
                .map(v => `- [${v.policy_id}] ${v.message} (${v.severity})`)
                .join('\n');

              summary.push('### Violations');
              summary.push(details || '- No violation details available');
              summary.push('');
              summary.push('Baseline enforcement is blocking until violations are fixed.');
            } else {
              summary.push('No policy violations detected.');
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary.join('\n')
            });

  baseline-enforcement:
    name: Baseline Enforcement
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build Baseline binary
        run: |
          go mod download
          go build -trimpath -o baseline ./cmd/baseline
          chmod +x baseline

      - name: Enforce policies
        run: ./baseline enforce
